import { create } from "zustand";

// ---- Types ----
export interface JobCard {
  image: string;
  title: string;
  company: string;
  category: string;
  jobCategoryid: string;
  location: string;
  type: string;
  salary: string;
  daysLeft: string;
  premium: boolean;
}

interface JobStore {
  jobs: JobCard[];
  getJobsByCategory: (categoryId: string) => JobCard[];
}

// ---- Store ----
export const useJobStore = create<JobStore>((set, get) => ({
  jobs: [
    // -------------------------
    // CATEGORY 1 — Development & IT
    // -------------------------
    {
      image: "leadWeb",
      title: "Lead Web3 Engineer",
      company: "Uxper",
      category: "Development and IT",
      jobCategoryid: "1",
      location: "New York",
      type: "Remote",
      salary: "$450 - $900/month",
      daysLeft: "75 days more to apply",
      premium: true,
    },
    {
      image: "devopsEngineer",
      title: "Senior DevOps Engineer",
      company: "CloudNova",
      category: "Development and IT",
      jobCategoryid: "1",
      location: "Remote",
      type: "Remote",
      salary: "$600 - $1200/month",
      daysLeft: "60 days left",
      premium: true,
    },
    {
      image: "aiEngineer",
      title: "AI & ML Engineer",
      company: "NeuroSoft",
      category: "Development and IT",
      jobCategoryid: "1",
      location: "Toronto",
      type: "Hybrid",
      salary: "$700 - $1500/month",
      daysLeft: "45 days left",
      premium: true,
    },
    {
      image: "qaLead",
      title: "QA Automation Lead",
      company: "TestLab",
      category: "Development and IT",
      jobCategoryid: "1",
      location: "Berlin",
      type: "Onsite",
      salary: "$400 - $800/month",
      daysLeft: "40 days left",
      premium: false,
    },
    {
      image: "gameDev",
      title: "Unity Game Developer",
      company: "PixelForge",
      category: "Development and IT",
      jobCategoryid: "1",
      location: "Tokyo",
      type: "Remote",
      salary: "$500 - $900/month",
      daysLeft: "72 days left",
      premium: false,
    },
    {
      image: "sysAdmin",
      title: "System Administrator",
      company: "ByteWorks",
      category: "Development and IT",
      jobCategoryid: "1",
      location: "Chicago",
      type: "Hybrid",
      salary: "$350 - $650/month",
      daysLeft: "56 days left",
      premium: false,
    },
    {
      image: "fullstack",
      title: "Full-Stack Engineer",
      company: "CodePilot",
      category: "Development and IT",
      jobCategoryid: "1",
      location: "Remote",
      type: "Remote",
      salary: "$700 - $1300/month",
      daysLeft: "20 days left",
      premium: true,
    },
    {
      image: "cloudEngineer",
      title: "Cloud Engineer (AWS)",
      company: "NimbusX",
      category: "Development and IT",
      jobCategoryid: "1",
      location: "London",
      type: "Hybrid",
      salary: "$600 - $1100/month",
      daysLeft: "90 days left",
      premium: false,
    },
    {
      image: "securityAnalyst",
      title: "Cybersecurity Analyst",
      company: "SecureTech",
      category: "Development and IT",
      jobCategoryid: "1",
      location: "Remote",
      type: "Remote",
      salary: "$650 - $1400/month",
      daysLeft: "45 days left",
      premium: true,
    },
    {
      image: "itSupport",
      title: "IT Support Specialist",
      company: "TechHelp",
      category: "Development and IT",
      jobCategoryid: "1",
      location: "Austin",
      type: "Onsite",
      salary: "$300 - $550/month",
      daysLeft: "30 days left",
      premium: false,
    },

    // -------------------------
    // CATEGORY 2 — Design & Creativity
    // -------------------------
    {
      image: "UXUI",
      title: "UX/UI Designer",
      company: "Figma Co.",
      category: "Design & Creativity",
      jobCategoryid: "2",
      location: "San Francisco",
      type: "Hybrid",
      salary: "$350 - $700/month",
      daysLeft: "50 days left",
      premium: false,
    },
    {
      image: "graphicDesigner",
      title: "Graphic Designer",
      company: "VectorLabs",
      category: "Design & Creativity",
      jobCategoryid: "2",
      location: "Paris",
      type: "Remote",
      salary: "$300 - $650/month",
      daysLeft: "40 days left",
      premium: false,
    },
    {
      image: "motionDesigner",
      title: "Motion Graphics Designer",
      company: "FrameShift",
      category: "Design & Creativity",
      jobCategoryid: "2",
      location: "Los Angeles",
      type: "Hybrid",
      salary: "$450 - $900/month",
      daysLeft: "60 days left",
      premium: true,
    },
    {
      image: "brandDesigner",
      title: "Brand Identity Designer",
      company: "IdentityHub",
      category: "Design & Creativity",
      jobCategoryid: "2",
      location: "London",
      type: "Remote",
      salary: "$400 - $800/month",
      daysLeft: "70 days left",
      premium: false,
    },
    {
      image: "illustrator",
      title: "Digital Illustrator",
      company: "SketchWorld",
      category: "Design & Creativity",
      jobCategoryid: "2",
      location: "Remote",
      type: "Remote",
      salary: "$350 - $600/month",
      daysLeft: "48 days left",
      premium: false,
    },
    {
      image: "3dArtist",
      title: "3D Artist",
      company: "RenderWave",
      category: "Design & Creativity",
      jobCategoryid: "2",
      location: "Canada",
      type: "Hybrid",
      salary: "$500 - $1000/month",
      daysLeft: "55 days left",
      premium: true,
    },
    {
      image: "videoEditor",
      title: "Senior Video Editor",
      company: "EditPro",
      category: "Design & Creativity",
      jobCategoryid: "2",
      location: "Sydney",
      type: "Onsite",
      salary: "$450 - $900/month",
      daysLeft: "34 days left",
      premium: false,
    },
    {
      image: "contentDesigner",
      title: "Content Designer",
      company: "StoryFlow",
      category: "Design & Creativity",
      jobCategoryid: "2",
      location: "Remote",
      type: "Remote",
      salary: "$300 - $700/month",
      daysLeft: "76 days left",
      premium: false,
    },
    {
      image: "productDesigner",
      title: "Product Designer",
      company: "Crafted UX",
      category: "Design & Creativity",
      jobCategoryid: "2",
      location: "Berlin",
      type: "Hybrid",
      salary: "$600 - $1200/month",
      daysLeft: "90 days left",
      premium: true,
    },
    {
      image: "uiAnimator",
      title: "UI Animator",
      company: "FlowMotion",
      category: "Design & Creativity",
      jobCategoryid: "2",
      location: "Tokyo",
      type: "Remote",
      salary: "$400 - $750/month",
      daysLeft: "20 days left",
      premium: false,
    },

    // -------------------------
    // CATEGORY 3 — Development
    // -------------------------
    {
      image: "SproductMarketer",
      title: "Backend Node.js Developer",
      company: "Techify",
      category: "Development",
      jobCategoryid: "3",
      location: "Remote",
      type: "Remote",
      salary: "$500 - $1000/month",
      daysLeft: "90 days left",
      premium: true,
    },
    {
      image: "frontendReact",
      title: "Frontend React Developer",
      company: "Webify",
      category: "Development",
      jobCategoryid: "3",
      location: "New York",
      type: "Hybrid",
      salary: "$550 - $900/month",
      daysLeft: "60 days left",
      premium: false,
    },
    {
      image: "mobileDev",
      title: "Flutter Mobile Developer",
      company: "AppNation",
      category: "Development",
      jobCategoryid: "3",
      location: "Remote",
      type: "Remote",
      salary: "$450 - $800/month",
      daysLeft: "40 days left",
      premium: false,
    },
    {
      image: "pythonDev",
      title: "Python Backend Engineer",
      company: "Datalink",
      category: "Development",
      jobCategoryid: "3",
      location: "Berlin",
      type: "Onsite",
      salary: "$600 - $1100/month",
      daysLeft: "75 days left",
      premium: true,
    },
    {
      image: "phpDeveloper",
      title: "PHP Laravel Developer",
      company: "StackBuilders",
      category: "Development",
      jobCategoryid: "3",
      location: "Toronto",
      type: "Hybrid",
      salary: "$450 - $900/month",
      daysLeft: "31 days left",
      premium: false,
    },
    {
      image: "goDev",
      title: "GoLang Developer",
      company: "GoWorks",
      category: "Development",
      jobCategoryid: "3",
      location: "Remote",
      type: "Remote",
      salary: "$700 - $1300/month",
      daysLeft: "44 days left",
      premium: true,
    },
    {
      image: "rustDev",
      title: "Rust Systems Developer",
      company: "SysCore",
      category: "Development",
      jobCategoryid: "3",
      location: "Boston",
      type: "Hybrid",
      salary: "$650 - $1400/month",
      daysLeft: "81 days left",
      premium: true,
    },
    {
      image: "sqlEngineer",
      title: "SQL Database Engineer",
      company: "DataHive",
      category: "Development",
      jobCategoryid: "3",
      location: "Amsterdam",
      type: "Onsite",
      salary: "$400 - $780/month",
      daysLeft: "57 days left",
      premium: false,
    },
    {
      image: "apiEngineer",
      title: "API Integration Engineer",
      company: "Connectly",
      category: "Development",
      jobCategoryid: "3",
      location: "Remote",
      type: "Remote",
      salary: "$550 - $1000/month",
      daysLeft: "39 days left",
      premium: false,
    },
    {
      image: "softwareArchitect",
      title: "Software Architect",
      company: "BuildStack",
      category: "Development",
      jobCategoryid: "3",
      location: "London",
      type: "Hybrid",
      salary: "$900 - $1700/month",
      daysLeft: "85 days left",
      premium: true,
    },
  ],

  getJobsByCategory: (categoryid: string) =>
    get().jobs.filter((job) => job.jobCategoryid === categoryid),
}));
